In [ ]:
# how to load in a file from someone else's google drive

# For downloading large files from Google Drive
# https://github.com/wkentaro/gdown
import gdown

# take sharing link from drive 
# paste here for reference:
# https://drive.google.com/file/d/1aHl1wSvf398chIuWMWaQt-qLcHaTY7Ly/view?usp=drivesdk

# copy the document id from above (betwen d/ and /view), and paste into where it says id=XXXXX below

# then download the file to your local workspace (NOTE: DOES NOT SAVE AFTER YOU DISCONNECT FROM RUNTIME!!!)
gdown.download('https://drive.google.com/uc?export=download&id=1C6yYYB-bxPFKIYtjJsiyw7jZZWK7PF_-', quiet=False) 

#https://drive.google.com/file/d/1C6yYYB-bxPFKIYtjJsiyw7jZZWK7PF_-/view?usp=sharing

Downloading...
From: https://drive.google.com/uc?export=download&id=1C6yYYB-bxPFKIYtjJsiyw7jZZWK7PF_-
To: /content/powerframes_final_df_tamertamed_withgendercount.json
100%|██████████| 407k/407k [00:00<00:00, 98.1MB/s]

'powerframes_final_df_tamertamed_withgendercount.json'

In [ ]:
import pandas as pd
import json

#convert JSON back to dataframe for analysis:

df_tamertamed_final = pd.read_json('powerframes_final_df_tamertamed_withgendercount.json')

df_tamertamed_final

,id,speaker,direction_type,position,act,scene,text,character_list,verb_lemmas,agency_pos,agency_neg,agency_equal,power_agent,power_equal,power_theme,speaker_gender,sd_gender,male_gender_count,female_gender_count
0,stg-0006,None,entrance,0,1,1,Enter Moroso Sophocles and Tranio with Rosemar...,"[Moroso, Sophocles, Tranio]",[enter],1,0,0,1,0,0,None,"[M, M, M]",3,0
1,sp-0008,Moroso,None,1,1,1,GOd give ’em joy,[],[give],1,0,0,1,0,0,M,[],0,0
2,sp-0010,Tranio,None,2,1,1,Amen,[],[],0,0,0,0,0,0,M,[],0,0
3,sp-0011,Sophocles,None,3,1,1,Amen say I too The Puddings now i’ th’ proof a...,[],"[say, ala, thou, work]",2,0,0,0,1,0,M,[],0,0
4,sp-0016,Tranio,None,4,1,1,’Tis too true Certain Methinks her father has ...,[],"[tis, deal, match, protest, pity]",3,0,0,1,2,0,M,[],0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1417,sp-3396,Rowland,None,1417,5,4,There shall not want my labor sir your money H...,[],"[want, ’s, undertake]",1,1,0,0,0,2,M,[],0,0
1418,sp-3398,Tranio,None,1418,5,4,Well I’ll trust her And glad I have so good a ...,[],"[trust, have]",0,2,0,1,0,1,M,[],0,0
1419,sp-3400,Rowland,None,1419,5,4,I’ll watch ye,[],[watch],0,0,1,1,0,0,M,[],0,0
1420,sp-3401,Petruchio,None,1420,5,4,Let’s in and drink of all hands and be jovial ...,[],"[let, drink, have, carry, marry, let, keep]",3,2,2,1,1,0,M,[],0,0
1421,stg-3404,None,exit,1421,5,4,Exeunt,[],[exeunt],0,0,0,0,0,0,None,[],0,0

In [ ]:
#line counts
  #by gender
  #by character (or speaker)

In [ ]:
#word counts

In [ ]:
#verb counts

In [ ]:
#sentence counts

In [ ]:
for index, row in df_tamertamed_final.iterrows():
  word_count = 0
  line_count = 1
  sentence_count = 0
  sentences = row['text'].split('.')
  for sentence in sentences:
    sentence_count +=1
  df_tamertamed_final.at[index, 'line_count'] = line_count
  df_tamertamed_final.at[index, 'sentence_count'] = sentence_count

for index, row in df_tamertamed_final.iterrows():
  word_count = 0
  words = row['text'].split(' ')
  for word in words:
    word_count +=1
  df_tamertamed_final.at[index, 'word_count'] = word_count

for index, row in df_tamertamed_final.iterrows():
  verb_count = 0
  verb_lemmas = row['verb_lemmas']
  for verb_lemma in verb_lemmas:
    verb_count +=1
    df_tamertamed_final.at[index, 'verb_count'] = verb_count

In [ ]:
df_tamertamed_final.head(30)

,id,speaker,direction_type,position,act,scene,text,character_list,verb_lemmas,agency_pos,...,power_equal,power_theme,speaker_gender,sd_gender,male_gender_count,female_gender_count,line_count,sentence_count,word_count,verb_count
0,stg-0006,None,entrance,0,1,1,Enter Moroso Sophocles and Tranio with Rosemar...,"[Moroso, Sophocles, Tranio]",[enter],1,...,0,0,None,"[M, M, M]",3,0,1.0,1.0,11.0,1.0
1,sp-0008,Moroso,None,1,1,1,GOd give ’em joy,[],[give],1,...,0,0,M,[],0,0,1.0,1.0,4.0,1.0
2,sp-0010,Tranio,None,2,1,1,Amen,[],[],0,...,0,0,M,[],0,0,1.0,1.0,1.0,NaN
3,sp-0011,Sophocles,None,3,1,1,Amen say I too The Puddings now i’ th’ proof a...,[],"[say, ala, thou, work]",2,...,1,0,M,[],0,0,1.0,1.0,28.0,4.0
4,sp-0016,Tranio,None,4,1,1,’Tis too true Certain Methinks her father has ...,[],"[tis, deal, match, protest, pity]",3,...,2,0,M,[],0,0,1.0,1.0,32.0,5.0
5,sp-0021,Moroso,None,5,1,1,Methinks now He’s not so terrible as people th...,[],"[’, think]",1,...,1,0,M,[],0,0,1.0,1.0,10.0,2.0
6,sp-0023,Sophocles,None,6,1,1,This old thief flatters out of mere devotion T...,[],[please],0,...,0,1,M,[],0,0,1.0,1.0,16.0,1.0
7,sp-0025,Tranio,None,7,1,1,But shall he have her,[],[have],0,...,0,0,M,[],0,0,1.0,1.0,5.0,1.0
8,sp-0026,Sophocles,None,8,1,1,Yes when I have Rome And yet the father’s for him,[],"[have, ’]",0,...,0,0,M,[],0,0,1.0,1.0,11.0,2.0
9,sp-0028,Moroso,None,9,1,1,I’ll assure ye I hold him a good man,[],"[assure, hold]",2,...,0,0,M,[],0,0,1.0,1.0,9.0,2.0
10,sp-0030,Sophocles,None,10,1,1,Yes sure a wealthy But whether a good woman’s ...,[],[],0,...,0,0,M,[],0,0,1.0,1.0,12.0,NaN
11,sp-0032,Tranio,None,11,1,1,Would ’twere no worse,[],[twere],0,...,0,0,M,[],0,0,1.0,1.0,4.0,1.0
12,sp-0033,Moroso,None,12,1,1,What though his other wife Out of her most abu...,[],"[cry, turn, force, blow, dost, follow, retain,...",4,...,0,1,M,[],0,0,1.0,1.0,51.0,8.0
13,sp-0040,Sophocles,None,13,1,1,I fear it,[],[fear],0,...,0,1,M,[],0,0,1.0,1.0,3.0,1.0
14,sp-0041,Tranio,None,14,1,1,So do I too And so far that if God had made me...,[],"[do, make]",2,...,0,0,M,[],0,0,1.0,1.0,20.0,2.0
15,sp-0044,Moroso,None,15,1,1,What would you do sir,[],[do],1,...,0,0,M,[],0,0,1.0,1.0,5.0,1.0
16,sp-0045,Tranio,None,16,1,1,I would learn to eat Coals with an angry Cat A...,[],"[learn, eat, prevent, tremble, be]",2,...,0,1,M,[],0,0,1.0,1.0,50.0,5.0
17,sp-0051,Sophocles,None,17,1,1,So I should think too,[],[think],1,...,1,0,M,[],0,0,1.0,1.0,5.0,1.0
18,sp-0052,Tranio,None,18,1,1,For yet the bare remembrance of his first wife...,[Petruchio],"[tell, make, start, cry, hide, walk, wear]",6,...,1,0,M,[M],1,0,1.0,1.0,65.0,7.0
19,sp-0060,Sophocles,None,19,1,1,He’s a good fellow And on my word I love him b...,[],"[’, love, think]",2,...,2,0,M,[],0,0,1.0,1.0,21.0,3.0
20,sp-0063,Tranio,None,20,1,1,His very frown if she but say her prayers Loud...,[],"[say, talk, make, ’s, do, eat, say, make, bid]",7,...,2,0,M,[],0,0,1.0,1.0,56.0,9.0
21,sp-0070,Sophocles,None,21,1,1,He will bury her Ten pound to twenty shillings...,[],[bury],0,...,0,0,M,[],0,0,1.0,1.0,13.0,1.0
22,sp-0072,Tranio,None,22,1,1,I’ll be your half,[],[],0,...,0,0,M,[],0,0,1.0,1.0,4.0,NaN
23,stg-0073,None,entrance,23,1,1,Enter Jaques with a pot of Wine,[],[enter],1,...,0,0,None,[],0,0,1.0,1.0,7.0,1.0
24,sp-0074,Moroso,None,24,1,1,He loves her most extremely And so long ’twill...,[],"[love, jaque]",1,...,1,0,M,[],0,0,1.0,1.0,21.0,2.0
25,sp-0077,Jaques,None,25,1,1,Yes certain This old sport must have eggs,[],[have],0,...,0,0,M,[],0,0,1.0,1.0,8.0,1.0
26,sp-0079,Sophocles,None,26,1,1,Not yet this ten days,[],[],0,...,0,0,M,[],0,0,1.0,1.0,5.0,NaN
27,sp-0080,Jaques,None,27,1,1,Sweet Gentlemen with Muscadel,[],[],0,...,0,0,M,[],0,0,1.0,1.0,4.0,NaN
28,sp-0081,Tranio,None,28,1,1,That’s right sir,[],[],0,...,0,0,M,[],0,0,1.0,1.0,3.0,NaN
29,sp-0082,Moroso,None,29,1,1,This fellow broods his Master speed ye Jaques,[],[brood],0,...,0,0,M,[],0,0,1.0,1.0,8.0,1.0

In [ ]:

###########
#BY GENDER#
###########
female_filter = df_tamertamed_final['speaker_gender'] == 'F'
male_filter = df_tamertamed_final['speaker_gender'] == 'M'

tamertamed_women = df_tamertamed_final[female_filter]
tamertamed_men = df_tamertamed_final[male_filter]

#line counts
tamertamed_men['line_count'].sum()
tamertamed_women['line_count'].sum()
#word counts
tamertamed_men['word_count'].sum()
tamertamed_women['word_count'].sum()
#verb counts
tamertamed_men['verb_count'].sum()
tamertamed_women['verb_count'].sum()
#sentence counts
tamertamed_men['sentence_count'].sum()
tamertamed_women['sentence_count'].sum()


d = {'line_count': [tamertamed_men['line_count'].sum(),tamertamed_women['line_count'].sum() ], 'word_count': [tamertamed_men['word_count'].sum(), tamertamed_women['word_count'].sum()], 'verb_count': [tamertamed_men['verb_count'].sum(), tamertamed_women['verb_count'].sum()], 'sentence_count': [tamertamed_men['sentence_count'].sum(), tamertamed_women['sentence_count'].sum()]}

df = pd.DataFrame(data=d)

df.index = ['tamertamed_men', 'tamertamed_women']

df

                  line_count  word_count  verb_count  sentence_count
tamertamed_men         887.0     14153.0      2166.0           889.0
tamertamed_women       393.0      8335.0      1276.0           393.0

In [ ]:
############
#BY SPEAKER#
############

#slice dataframe by speaker
bianca_speaker_filter = df_tamertamed_final['speaker'] == 'Bianca'
bianca_speaker_slice = df_tamertamed_final[bianca_speaker_filter]

maria_speaker_filter = df_tamertamed_final['speaker'] == 'Maria'
maria_speaker_slice = df_tamertamed_final[maria_speaker_filter]

petruchio_speaker_filter = df_tamertamed_final['speaker'] == 'Petruchio'
petruchio_speaker_slice = df_tamertamed_final[petruchio_speaker_filter]

livia_speaker_filter = df_tamertamed_final['speaker'] == 'Livia'
livia_speaker_slice = df_tamertamed_final[livia_speaker_filter]

rowland_speaker_filter = df_tamertamed_final['speaker'] == 'Rowland'
rowland_speaker_slice = df_tamertamed_final[rowland_speaker_filter]

moroso_speaker_filter = df_tamertamed_final['speaker'] == 'Moroso'
moroso_speaker_slice = df_tamertamed_final[moroso_speaker_filter]

tranio_speaker_filter = df_tamertamed_final['speaker'] == 'Tranio'
tranio_speaker_slice = df_tamertamed_final[tranio_speaker_filter]

sophocles_speaker_filter = df_tamertamed_final['speaker'] == 'Sophocles'
sophocles_speaker_slice = df_tamertamed_final[sophocles_speaker_filter]

jaques_speaker_filter = df_tamertamed_final['speaker'] == 'Jaques'
jaques_speaker_slice = df_tamertamed_final[jaques_speaker_filter]

petronius_speaker_filter = df_tamertamed_final['speaker'] == 'Petronius'
petronius_speaker_slice = df_tamertamed_final[petronius_speaker_filter]

pedro_speaker_filter = df_tamertamed_final['speaker'] == 'Pedro'
pedro_speaker_slice = df_tamertamed_final[pedro_speaker_filter]


#note this isn't everyone... 
d2 = {'line_count': 
#line counts
[bianca_speaker_slice['line_count'].sum(),petruchio_speaker_slice['line_count'].sum(),
maria_speaker_slice['line_count'].sum(),
livia_speaker_slice['line_count'].sum(),
rowland_speaker_slice['line_count'].sum(),
moroso_speaker_slice['line_count'].sum(),
tranio_speaker_slice['line_count'].sum(),
sophocles_speaker_slice['line_count'].sum(),
jaques_speaker_slice['line_count'].sum(),
petronius_speaker_slice['line_count'].sum(),
pedro_speaker_slice['line_count'].sum()],

#word counts
'word_count':
[bianca_speaker_slice['word_count'].sum(),petruchio_speaker_slice['word_count'].sum(),
maria_speaker_slice['word_count'].sum(),
livia_speaker_slice['word_count'].sum(),
rowland_speaker_slice['word_count'].sum(),
moroso_speaker_slice['word_count'].sum(),
tranio_speaker_slice['word_count'].sum(),
sophocles_speaker_slice['word_count'].sum(),
jaques_speaker_slice['word_count'].sum(),
petronius_speaker_slice['word_count'].sum(),
pedro_speaker_slice['word_count'].sum()],

#verb counts
'verb_count':
[bianca_speaker_slice['verb_count'].sum(), petruchio_speaker_slice['verb_count'].sum(),
maria_speaker_slice['verb_count'].sum(),
livia_speaker_slice['verb_count'].sum(),
rowland_speaker_slice['verb_count'].sum(),
moroso_speaker_slice['verb_count'].sum(),
tranio_speaker_slice['verb_count'].sum(),
sophocles_speaker_slice['verb_count'].sum(),
jaques_speaker_slice['verb_count'].sum(),
petronius_speaker_slice['verb_count'].sum(),
pedro_speaker_slice['verb_count'].sum()],

#sentence counts
'sentence_count':
[bianca_speaker_slice['sentence_count'].sum(),petruchio_speaker_slice['verb_count'].sum(),
maria_speaker_slice['sentence_count'].sum(),
livia_speaker_slice['sentence_count'].sum(),
rowland_speaker_slice['sentence_count'].sum(),
moroso_speaker_slice['sentence_count'].sum(),
tranio_speaker_slice['sentence_count'].sum(),
sophocles_speaker_slice['sentence_count'].sum(),
jaques_speaker_slice['sentence_count'].sum(),
petronius_speaker_slice['sentence_count'].sum(),
pedro_speaker_slice['sentence_count'].sum()]}


df2 = pd.DataFrame(data=d2)

df2.index = ['Bianca', 'Petruchio','Maria','Livia','Rowland','Moroso','Tranio','Sophocles','Jaques','Petronius','Pedro']

df2

           line_count  word_count  verb_count  sentence_count
Bianca          117.0      2028.0       315.0           117.0
Petruchio       187.0      4787.0       725.0           725.0
Maria           151.0      4233.0       656.0           151.0
Livia           102.0      1711.0       263.0           102.0
Rowland         155.0      2145.0       332.0           155.0
Moroso           72.0       999.0       136.0            73.0
Tranio          112.0      1006.0       159.0           112.0
Sophocles       104.0      1236.0       214.0           104.0
Jaques           76.0      1737.0       241.0            76.0
Petronius       124.0      1572.0       263.0           125.0
Pedro            49.0       598.0        86.0            49.0

In [ ]:
#save both new dataframes to JSON format

#SAVE TO JSON!!!

##############
#BY gender df#
##############

# storing the data in JSON format
df.to_json('df_gender_line_word_verb_sentence_counts.json', orient = 'split', compression = 'infer', index = 'true')
 
# reading the JSON file
df_gender_line_word_verb_sentence_counts = pd.read_json('df_gender_line_word_verb_sentence_counts.json', orient ='split', compression = 'infer')

#I can see them when I access my google drive on the left side now as "file.json"

# Now you should save the new dataframe to your google drive for safe-keeping
from google.colab import drive
drive.mount('/content/gdrive')

filename = "/content/df_gender_line_word_verb_sentence_counts.json"

################
#By speaker df##
################

# storing the data in JSON format
df2.to_json('df2_speaker_line_word_verb_sentence_counts.json', orient = 'split', compression = 'infer', index = 'true')

# reading the JSON file
df2_speaker_line_word_verb_sentence_counts = pd.read_json('df2_speaker_line_word_verb_sentence_counts.json', orient ='split', compression = 'infer')

# Now you should save the new dataframe to your google drive for safe-keeping
from google.colab import drive
drive.mount('/content/gdrive')

filename = "/content/df2_gender_line_word_verb_sentence_counts.json"

Mounted at /content/gdrive
Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [ ]:
df_tamertamed_final.head(50)

,id,speaker,direction_type,position,act,scene,text,character_list,verb_lemmas,agency_pos,...,power_equal,power_theme,speaker_gender,sd_gender,male_gender_count,female_gender_count,line_count,sentence_count,word_count,verb_count
0,stg-0006,None,entrance,0,1,1,Enter Moroso Sophocles and Tranio with Rosemar...,"[Moroso, Sophocles, Tranio]",[enter],1,...,0,0,None,"[M, M, M]",3,0,1.0,1.0,11.0,1.0
1,sp-0008,Moroso,None,1,1,1,GOd give ’em joy,[],[give],1,...,0,0,M,[],0,0,1.0,1.0,4.0,1.0
2,sp-0010,Tranio,None,2,1,1,Amen,[],[],0,...,0,0,M,[],0,0,1.0,1.0,1.0,NaN
3,sp-0011,Sophocles,None,3,1,1,Amen say I too The Puddings now i’ th’ proof a...,[],"[say, ala, thou, work]",2,...,1,0,M,[],0,0,1.0,1.0,28.0,4.0
4,sp-0016,Tranio,None,4,1,1,’Tis too true Certain Methinks her father has ...,[],"[tis, deal, match, protest, pity]",3,...,2,0,M,[],0,0,1.0,1.0,32.0,5.0
5,sp-0021,Moroso,None,5,1,1,Methinks now He’s not so terrible as people th...,[],"[’, think]",1,...,1,0,M,[],0,0,1.0,1.0,10.0,2.0
6,sp-0023,Sophocles,None,6,1,1,This old thief flatters out of mere devotion T...,[],[please],0,...,0,1,M,[],0,0,1.0,1.0,16.0,1.0
7,sp-0025,Tranio,None,7,1,1,But shall he have her,[],[have],0,...,0,0,M,[],0,0,1.0,1.0,5.0,1.0
8,sp-0026,Sophocles,None,8,1,1,Yes when I have Rome And yet the father’s for him,[],"[have, ’]",0,...,0,0,M,[],0,0,1.0,1.0,11.0,2.0
9,sp-0028,Moroso,None,9,1,1,I’ll assure ye I hold him a good man,[],"[assure, hold]",2,...,0,0,M,[],0,0,1.0,1.0,9.0,2.0
10,sp-0030,Sophocles,None,10,1,1,Yes sure a wealthy But whether a good woman’s ...,[],[],0,...,0,0,M,[],0,0,1.0,1.0,12.0,NaN
11,sp-0032,Tranio,None,11,1,1,Would ’twere no worse,[],[twere],0,...,0,0,M,[],0,0,1.0,1.0,4.0,1.0
12,sp-0033,Moroso,None,12,1,1,What though his other wife Out of her most abu...,[],"[cry, turn, force, blow, dost, follow, retain,...",4,...,0,1,M,[],0,0,1.0,1.0,51.0,8.0
13,sp-0040,Sophocles,None,13,1,1,I fear it,[],[fear],0,...,0,1,M,[],0,0,1.0,1.0,3.0,1.0
14,sp-0041,Tranio,None,14,1,1,So do I too And so far that if God had made me...,[],"[do, make]",2,...,0,0,M,[],0,0,1.0,1.0,20.0,2.0
15,sp-0044,Moroso,None,15,1,1,What would you do sir,[],[do],1,...,0,0,M,[],0,0,1.0,1.0,5.0,1.0
16,sp-0045,Tranio,None,16,1,1,I would learn to eat Coals with an angry Cat A...,[],"[learn, eat, prevent, tremble, be]",2,...,0,1,M,[],0,0,1.0,1.0,50.0,5.0
17,sp-0051,Sophocles,None,17,1,1,So I should think too,[],[think],1,...,1,0,M,[],0,0,1.0,1.0,5.0,1.0
18,sp-0052,Tranio,None,18,1,1,For yet the bare remembrance of his first wife...,[Petruchio],"[tell, make, start, cry, hide, walk, wear]",6,...,1,0,M,[M],1,0,1.0,1.0,65.0,7.0
19,sp-0060,Sophocles,None,19,1,1,He’s a good fellow And on my word I love him b...,[],"[’, love, think]",2,...,2,0,M,[],0,0,1.0,1.0,21.0,3.0
20,sp-0063,Tranio,None,20,1,1,His very frown if she but say her prayers Loud...,[],"[say, talk, make, ’s, do, eat, say, make, bid]",7,...,2,0,M,[],0,0,1.0,1.0,56.0,9.0
21,sp-0070,Sophocles,None,21,1,1,He will bury her Ten pound to twenty shillings...,[],[bury],0,...,0,0,M,[],0,0,1.0,1.0,13.0,1.0
22,sp-0072,Tranio,None,22,1,1,I’ll be your half,[],[],0,...,0,0,M,[],0,0,1.0,1.0,4.0,NaN
23,stg-0073,None,entrance,23,1,1,Enter Jaques with a pot of Wine,[],[enter],1,...,0,0,None,[],0,0,1.0,1.0,7.0,1.0
24,sp-0074,Moroso,None,24,1,1,He loves her most extremely And so long ’twill...,[],"[love, jaque]",1,...,1,0,M,[],0,0,1.0,1.0,21.0,2.0
25,sp-0077,Jaques,None,25,1,1,Yes certain This old sport must have eggs,[],[have],0,...,0,0,M,[],0,0,1.0,1.0,8.0,1.0
26,sp-0079,Sophocles,None,26,1,1,Not yet this ten days,[],[],0,...,0,0,M,[],0,0,1.0,1.0,5.0,NaN
27,sp-0080,Jaques,None,27,1,1,Sweet Gentlemen with Muscadel,[],[],0,...,0,0,M,[],0,0,1.0,1.0,4.0,NaN
28,sp-0081,Tranio,None,28,1,1,That’s right sir,[],[],0,...,0,0,M,[],0,0,1.0,1.0,3.0,NaN
29,sp-0082,Moroso,None,29,1,1,This fellow broods his Master speed ye Jaques,[],[brood],0,...,0,0,M,[],0,0,1.0,1.0,8.0,1.0
30,sp-0083,Sophocles,None,30,1,1,We shall be for you presently,[],[],0,...,0,0,M,[],0,0,1.0,1.0,6.0,NaN
31,sp-0084,Jaques,None,31,1,1,Your worships Shall have it rich and neat and ...,[],"[have, see, run]",1,...,1,0,M,[],0,0,1.0,1.0,38.0,3.0
32,sp-0089,Moroso,None,32,1,1,So sir,[],[],0,...,0,0,M,[],0,0,1.0,1.0,2.0,NaN
33,sp-0090,Jaques,None,33,1,1,Upon my little honesty your Mistress If I have...,[],"[have, think]",1,...,1,0,M,[],0,0,1.0,1.0,26.0,2.0
34,sp-0094,Moroso,None,34,1,1,Y’ are merry,[],[],0,...,0,0,M,[],0,0,1.0,1.0,3.0,NaN
35,sp-0095,Jaques,None,35,1,1,Would I were wise too so God bless your worship,[],[bless],1,...,1,0,M,[],0,0,1.0,1.0,10.0,1.0
36,sp-0096,Tranio,None,36,1,1,The fellow tells you true,[],[tell],1,...,1,0,M,[],0,0,1.0,1.0,5.0,1.0
37,stg-0096,None,exit,37,1,1,Exit Jaques,[],[],0,...,0,0,None,[],0,0,1.0,1.0,2.0,NaN
38,sp-0097,Sophocles,None,38,1,1,When is the day man Come come you’ll steal a m...,[],"[come, come, steal]",3,...,0,0,M,[],0,0,1.0,1.0,11.0,3.0
39,sp-0099,Moroso,None,39,1,1,Nay believe me But when her father pleases I a...,[],"[believe, please, know]",0,...,0,2,M,[],0,0,1.0,1.0,18.0,3.0
40,sp-0102,Tranio,None,40,1,1,Why not now One charge had served for both,[],[serve],0,...,0,1,M,[],0,0,1.0,1.0,9.0,1.0
41,sp-0104,Moroso,None,41,1,1,There’s reason in ’t,[],[’],0,...,0,0,M,[],0,0,1.0,1.0,4.0,1.0
42,sp-0105,Sophocles,None,42,1,1,Called Rowland,[Rowland],[call],1,...,0,1,M,[M],1,0,1.0,1.0,2.0,1.0
43,sp-0106,Moroso,None,43,1,1,Will ye walk They’ll think we are lost Come Ge...,[],"[walk, think, lose]",2,...,1,1,M,[],0,0,1.0,1.0,10.0,3.0
44,sp-0108,Tranio,None,44,1,1,You have whipped him now,[],[whip],1,...,0,0,M,[],0,0,1.0,1.0,5.0,1.0
45,sp-0109,Sophocles,None,45,1,1,So will he never the wench I hope,[],[hope],0,...,0,1,M,[],0,0,1.0,1.0,8.0,1.0
46,sp-0110,Tranio,None,46,1,1,I wish it,[],[wish],0,...,0,1,M,[],0,0,1.0,1.0,3.0,1.0
47,stg-0110,None,exit,47,1,1,Exeunt,[],[exeunt],0,...,0,0,None,[],0,0,1.0,1.0,1.0,1.0
48,stg-0112,None,entrance,48,1,2,Enter Rowland and Livia,"[Rowland, Livia]",[enter],1,...,0,0,None,"[M, F]",1,1,1.0,1.0,4.0,1.0
49,sp-0113,Rowland,None,49,1,2,Now Livia if you’ll go away tonight If your af...,[Livia],"[go, make]",1,...,1,0,M,[F],0,1,1.0,1.0,15.0,2.0