In [ ]:
# how to load in a file from someone else's google drive

# For downloading large files from Google Drive
# https://github.com/wkentaro/gdown
import gdown

# take sharing link from drive 
# paste here for reference:
# https://drive.google.com/file/d/1aHl1wSvf398chIuWMWaQt-qLcHaTY7Ly/view?usp=drivesdk

# copy the document id from above (betwen d/ and /view), and paste into where it says id=XXXXX below

# then download the file to your local workspace (NOTE: DOES NOT SAVE AFTER YOU DISCONNECT FROM RUNTIME!!!)
gdown.download('https://drive.google.com/uc?export=download&id=1C6yYYB-bxPFKIYtjJsiyw7jZZWK7PF_-', quiet=False) 

#https://drive.google.com/file/d/1C6yYYB-bxPFKIYtjJsiyw7jZZWK7PF_-/view?usp=sharing

Downloading...
From: https://drive.google.com/uc?export=download&id=1C6yYYB-bxPFKIYtjJsiyw7jZZWK7PF_-
To: /content/powerframes_final_df_tamertamed_withgendercount.json
100%|██████████| 407k/407k [00:00<00:00, 84.3MB/s]

'powerframes_final_df_tamertamed_withgendercount.json'

In [ ]:
import pandas as pd
import json

#convert JSON back to dataframe for analysis:

df_tamertamed_final = pd.read_json('powerframes_final_df_tamertamed_withgendercount.json')

df_tamertamed_final

,id,speaker,direction_type,position,act,scene,text,character_list,verb_lemmas,agency_pos,agency_neg,agency_equal,power_agent,power_equal,power_theme,speaker_gender,sd_gender,male_gender_count,female_gender_count
0,stg-0006,None,entrance,0,1,1,Enter Moroso Sophocles and Tranio with Rosemar...,"[Moroso, Sophocles, Tranio]",[enter],1,0,0,1,0,0,None,"[M, M, M]",3,0
1,sp-0008,Moroso,None,1,1,1,GOd give ’em joy,[],[give],1,0,0,1,0,0,M,[],0,0
2,sp-0010,Tranio,None,2,1,1,Amen,[],[],0,0,0,0,0,0,M,[],0,0
3,sp-0011,Sophocles,None,3,1,1,Amen say I too The Puddings now i’ th’ proof a...,[],"[say, ala, thou, work]",2,0,0,0,1,0,M,[],0,0
4,sp-0016,Tranio,None,4,1,1,’Tis too true Certain Methinks her father has ...,[],"[tis, deal, match, protest, pity]",3,0,0,1,2,0,M,[],0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1417,sp-3396,Rowland,None,1417,5,4,There shall not want my labor sir your money H...,[],"[want, ’s, undertake]",1,1,0,0,0,2,M,[],0,0
1418,sp-3398,Tranio,None,1418,5,4,Well I’ll trust her And glad I have so good a ...,[],"[trust, have]",0,2,0,1,0,1,M,[],0,0
1419,sp-3400,Rowland,None,1419,5,4,I’ll watch ye,[],[watch],0,0,1,1,0,0,M,[],0,0
1420,sp-3401,Petruchio,None,1420,5,4,Let’s in and drink of all hands and be jovial ...,[],"[let, drink, have, carry, marry, let, keep]",3,2,2,1,1,0,M,[],0,0
1421,stg-3404,None,exit,1421,5,4,Exeunt,[],[exeunt],0,0,0,0,0,0,None,[],0,0

In [ ]:
#create a new dataframe with just speaker and lemma verbs
df2 = df_tamertamed_final[['speaker','verb_lemmas','speaker_gender']]

df2

        speaker                                  verb_lemmas speaker_gender
0          None                                      [enter]           None
1        Moroso                                       [give]              M
2        Tranio                                           []              M
3     Sophocles                       [say, ala, thou, work]              M
4        Tranio            [tis, deal, match, protest, pity]              M
...         ...                                          ...            ...
1417    Rowland                        [want, ’s, undertake]              M
1418     Tranio                                [trust, have]              M
1419    Rowland                                      [watch]              M
1420  Petruchio  [let, drink, have, carry, marry, let, keep]              M
1421       None                                     [exeunt]           None

[1422 rows x 3 columns]

In [ ]:
#for item in character list
  #if new verb append to list
  #count most frequent verbs
  #slice data frame, count most frequent verbs by gender, by speaker


male_characters = ['Moroso','Sophocles', 'Tranio', 'Jaques', 'Doctor', 'Pedro', 'Petruchio', 'Rowland', 'Servant', 'Sophocles', 'Watchmen','Petronius'] 
female_characters = ['Bianca', 'CityWife', "CountryWife", "Livia", "Maids", "Maria"] 



#create list of all verbs used?
verb_lemma_list = []
for index, row in df2.iterrows(): 
  for word in row['verb_lemmas']:
    if word not in verb_lemma_list:
      verb_lemma_list.append(word)

#  print(verb_lemma_list)

  for index2, row2 in df2.iterrows():
    for male_character in male_characters:
      verb_count = 0
      if male_character == row['speaker']:
        for verb in row['verb_lemmas']:
          if verb in verb_lemma_list:
            verb_count +=1
      #increase counter by one for each verb and each time that speaker uses that verb
    df2.loc[index,'verb_count'] = verb_count

df2

#try at next?

/usr/local/lib/python3.8/dist-packages/pandas/core/indexing.py:1684: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = infer_fill_value(value)
/usr/local/lib/python3.8/dist-packages/pandas/core/indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

KeyboardInterrupt: ignored

In [ ]:
df2.head(50)

In [ ]:
df2['verb_lemmas'].value_counts()

TypeError: ignored

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[]                                             328
[enter]                                         50
[have]                                          25
[exeunt]                                        20
[do]                                            19
                                              ...
[hear, acquaint]                                 1
[sell, take]                                     1
[choke]                                          1
[tell, have, eat]                                1
[let, drink, have, carry, marry, let, keep]      1
Name: verb_lemmas, Length: 801, dtype: int64

In [ ]:
#create a list of all verbs to get top verbs overall (and do append repeats therefore)?

verb_lemma_list2 = []
for index, row in df2.iterrows(): 
  for word in row['verb_lemmas']:
      verb_lemma_list2.append(word)

In [ ]:
b = {}
for item in verb_lemma_list2:
    b[item] = b.get(item, 0) + 1

In [ ]:
b

{'enter': 58,
 'give': 58,
 'say': 51,
 'ala': 2,
 'thou': 1,
 'work': 6,
 'tis': 43,
 'deal': 9,
 'match': 2,
 'protest': 2,
 'pity': 6,
 '’': 79,
 'think': 63,
 'please': 13,
 'have': 152,
 'assure': 3,
 'hold': 10,
 'twere': 3,
 'cry': 17,
 'turn': 11,
 'force': 6,
 'blow': 5,
 'dost': 9,
 'follow': 14,
 'retain': 1,
 'bury': 4,
 'fear': 17,
 'do': 110,
 'make': 93,
 'learn': 7,
 'eat': 9,
 'prevent': 1,
 'tremble': 2,
 'be': 33,
 'tell': 60,
 'start': 4,
 'hide': 3,
 'walk': 9,
 'wear': 9,
 'love': 48,
 'talk': 16,
 '’s': 14,
 'bid': 5,
 'jaque': 3,
 'brood': 1,
 'see': 57,
 'run': 16,
 'bless': 6,
 'come': 83,
 'steal': 5,
 'believe': 34,
 'know': 74,
 'serve': 8,
 'call': 12,
 'lose': 22,
 'whip': 1,
 'hope': 12,
 'wish': 11,
 'exeunt': 20,
 'go': 79,
 'saint': 1,
 'take': 63,
 'care': 7,
 'overrun': 1,
 'flatter': 3,
 'leave': 33,
 'fly': 8,
 'enjoy': 6,
 'let': 75,
 'admit': 2,
 'bring': 14,
 'look': 35,
 'show': 13,
 'win': 12,
 'whore': 3,
 'find': 40,
 'draw': 10,
 'forgive': 10,
 'kiss': 15,
 'lay': 4,
 'grasp': 1,
 'thank': 13,
 'o': 3,
 'merry': 1,
 'lie': 21,
 'sit': 2,
 'stamp': 1,
 'bear': 20,
 'buy': 5,
 'doubt': 5,
 'pule': 1,
 'fail': 3,
 'carry': 13,
 'content': 4,
 'credit': 2,
 'hear': 48,
 'hang': 26,
 'cross': 4,
 'hatch': 3,
 'blush': 3,
 'continual': 1,
 'set': 12,
 'bind': 1,
 'persuade': 2,
 'suffer': 9,
 'stay': 25,
 'urge': 5,
 'redeem': 1,
 'leap': 4,
 'continue': 5,
 'lead': 2,
 'view': 4,
 'wench': 2,
 'up': 1,
 'rouse': 1,
 'sweat': 3,
 'rise': 4,
 'starve': 6,
 'tie': 4,
 'seem': 8,
 'marry': 21,
 'mark': 11,
 'mean': 25,
 'keep': 24,
 'fast': 3,
 'perceive': 2,
 'Divest': 1,
 'scoop': 1,
 'unlock': 1,
 'pull': 3,
 'guess': 3,
 'strengthen': 1,
 'knit': 1,
 'get': 38,
 'pray': 36,
 'swear': 16,
 'shame': 3,
 'aim': 3,
 'live': 17,
 'become': 4,
 'create': 1,
 'name': 1,
 'die': 10,
 'hath': 2,
 'regard': 1,
 'desire': 3,
 'founder': 1,
 'fle': 4,
 'spur': 3,
 'reclaim': 2,
 'confirm': 4,
 'cast': 5,
 'undertake': 3,
 'reach': 5,
 'bend': 2,
 'list': 2,
 'mold': 1,
 'want': 16,
 'master': 1,
 'chronicle': 2,
 'confess': 7,
 'hate': 8,
 'cuckold': 1,
 'deserve': 9,
 'sleep': 4,
 'intend': 2,
 'promise': 1,
 'trouble': 4,
 'wind': 1,
 'commend': 2,
 'hinder': 1,
 'end': 5,
 'visit': 2,
 'deliver': 3,
 'like': 9,
 'knock': 5,
 'observe': 4,
 'whisper': 1,
 'ear': 1,
 'break': 16,
 'purpose': 2,
 'clap': 5,
 'breath': 1,
 'despise': 3,
 'butter': 2,
 'belabor': 1,
 'quench': 2,
 'sink': 2,
 'miscarry': 1,
 'rifle': 1,
 'entail': 1,
 'try': 6,
 'cut': 4,
 'drop': 1,
 'untile': 1,
 'express': 1,
 'lodge': 1,
 'barricado': 1,
 'victual': 2,
 'lock': 5,
 'guard': 2,
 'plant': 2,
 'batter': 2,
 'stand': 18,
 'march': 4,
 'cock': 1,
 'satisfy': 1,
 'command': 5,
 'venture': 3,
 'mount': 3,
 'laugh': 4,
 'beat': 12,
 'fortify': 3,
 'dare': 14,
 'cool': 2,
 'scape': 3,
 'scour': 1,
 'answer': 5,
 'duck': 1,
 'charge': 6,
 'tantara': 1,
 'line': 1,
 'daughter': 1,
 'entrench': 1,
 'offend': 1,
 'use': 9,
 'fain': 2,
 'reprieve': 1,
 'trim': 2,
 'wilt': 4,
 'seal': 5,
 'bestow': 1,
 'fetch': 3,
 'yield': 2,
 'wive': 1,
 'wake': 1,
 'owe': 5,
 'choose': 5,
 'pay': 9,
 'play': 8,
 'prate': 1,
 'brew': 1,
 'stock': 1,
 'untie': 2,
 'tend': 2,
 'consider': 2,
 'remember': 2,
 'exact': 1,
 'rave': 2,
 'trot': 1,
 'article': 1,
 'read': 7,
 'observed': 1,
 'understand': 7,
 'feed': 1,
 'tender': 1,
 'melt': 1,
 'add': 1,
 'appear': 4,
 'flay': 3,
 'send': 18,
 'wonder': 3,
 'handle': 1,
 'mingle': 2,
 'speak': 19,
 'watch': 6,
 'wither': 2,
 'rebel': 2,
 'put': 11,
 'shake': 4,
 'quarter': 2,
 'tame': 3,
 'devil': 1,
 'stick': 2,
 'touch': 4,
 'beleaguer': 1,
 'recreant': 1,
 'stop': 3,
 'succor': 1,
 'grow': 9,
 'provide': 3,
 'fire': 1,
 'jade': 1,
 'beseech': 6,
 'pardon': 1,
 'tune': 1,
 'ail': 2,
 'relieve': 2,
 'spoil': 4,
 'ride': 9,
 'meet': 9,
 'jest': 1,
 'defy': 6,
 'braver': 1,
 'meditate': 1,
 'leapt': 1,
 'retire': 1,
 'shun': 1,
 'excite': 1,
 'yonder': 1,
 'discover': 7,
 'salute': 1,
 'save': 11,
 'kennel': 1,
 'discontent': 1,
 'sue': 2,
 'cover': 1,
 'hunt': 1,
 'grace': 1,
 'accept': 2,
 'wring': 2,
 'token': 1,
 'fumble': 1,
 'baffle': 1,
 'cure': 4,
 'form': 1,
 'slight': 1,
 'reckon': 3,
 'forget': 4,
 'bespeak': 3,
 'ye': 1,
 'warrant': 3,
 'handsel': 1,
 'groan': 1,
 'peruse': 4,
 'comfort': 2,
 'ship': 3,
 'sail': 1,
 'deceive': 4,
 'shift': 2,
 'seize': 3,
 'cheat': 1,
 'Put': 1,
 'inveigle': 1,
 'loose': 1,
 'entertain': 3,
 'burn': 2,
 'seek': 5,
 'root': 1,
 'second': 1,
 'trip': 2,
 'kill': 12,
 'feel': 4,
 'dry': 2,
 'acknowledge': 1,
 'rob': 1,
 'consume': 1,
 'prove': 3,
 'load': 1,
 'rail': 5,
 'smell': 1,
 'undo': 8,
 'curse': 4,
 'drink': 6,
 'pinch': 2,
 'toss': 2,
 'flame': 1,
 'o’er': 1,
 'repent': 4,
 'behold': 1,
 'defile': 1,
 'favor': 2,
 'arrive': 3,
 'acquaint': 1,
 'sell': 1,
 'choke': 1,
 'fame': 1,
 'practice': 1,
 'gall': 1,
 'rowland': 1,
 'count': 1,
 'ease': 2,
 'grant': 4,
 'imagine': 1,
 'stiff': 1,
 'endure': 3,
 'pillow': 1,
 'lull': 1,
 'tabor': 1,
 'creep': 2,
 'methink': 1,
 'err': 1,
 'brace': 1,
 'pamper': 1,
 'arm': 1,
 'swarm': 1,
 'destroy': 1,
 'catch': 2,
 'heave': 1,
 'fall': 5,
 'aspire': 1,
 'attempt': 1,
 'batt’re': 1,
 'fight': 1,
 'erect': 2,
 'convert': 1,
 'smoke': 1,
 'council': 1,
 'advise': 1,
 'avoid': 4,
 'cart': 2,
 'resolve': 1,
 'woo': 2,
 'offer': 4,
 'warm': 1,
 'grapple': 1,
 'paint': 1,
 'flounder': 1,
 'flaunt': 1,
 'firk': 2,
 'tuck': 1,
 'peep': 1,
 'exceed': 3,
 'utter': 1,
 'espouse': 1,
 'outwear': 2,
 'treat': 1,
 'divide': 1,
 'pile': 1,
 'peace': 1,
 'tongue': 1,
 'inherit': 1,
 'fill': 1,
 'degrade': 1,
 'tear': 1,
 'videlicet': 1,
 'return': 2,
 'man': 2,
 'prospect': 1,
 'stumble': 1,
 'compel': 1,
 'expect': 2,
 'dispose': 2,
 'appoint': 1,
 'importune': 1,
 'humor': 1,
 'ratify': 2,
 'alter': 2,
 'insert': 1,
 'grudge': 1,
 'ordain': 3,
 'bow': 1,
 'poison': 2,
 'begin': 8,
 'write': 3,
 'better': 1,
 'dance': 1,
 'conceive': 6,
 'begin’st': 1,
 'worship': 1,
 'fling': 1,
 'braid': 1,
 'sigh': 1,
 'cant': 1,
 'deign': 2,
 'lick': 2,
 'hit': 2,
 'delight': 1,
 'vow': 4,
 'reconcile': 1,
 'stint': 1,
 'bestride': 1,
 'threaten': 1,
 'twa': 1,
 'cram': 1,
 'back': 2,
 'hallow': 1,
 'tumble': 1,
 'rid': 3,
 'simper': 1,
 'belch': 1,
 'tipple': 1,
 'roar': 2,
 'grease': 1,
 'sullen': 1,
 'filch': 1,
 'rascal': 1,
 'pass': 3,
 'require': 3,
 'struggle': 2,
 'wash': 1,
 'weary': 1,
 'consent': 1,
 'appetite': 1,
 'dispatch': 1,
 'nettle': 1,
 'help': 3,
 'tilt': 1,
 'strive': 1,
 'purchase': 3,
 'close': 1,
 'shower': 2,
 'gnaw': 1,
 'preserve': 2,
 'study': 2,
 'dress': 2,
 'pluck': 1,
 'build': 2,
 'cost': 2,
 'battle': 1,
 'gild': 2,
 'your': 1,
 'weigh': 1,
 'descend': 1,
 'mistake': 3,
 'dwell': 1,
 'abuse': 8,
 'disobedient': 1,
 'drag': 2,
 'face': 1,
 'ask': 1,
 'winter': 1,
 'stray': 1,
 'reign': 2,
 'warn': 2,
 'mix': 1,
 'worry': 1,
 'ache': 1,
 'perish': 3,
 'displante': 1,
 'fix': 1,
 'spend': 1,
 'fie': 1,
 'oftentime': 1,
 'induce': 1,
 'farewell': 2,
 'shoot': 3,
 'wipe': 1,
 'fare': 5,
 'raise': 3,
 'fellow': 2,
 'infect': 3,
 'attend': 1,
 'fright': 1,
 'ho': 1,
 'thee': 1,
 'distinguish': 2,
 'misdoubt': 1,
 'light': 1,
 'open': 3,
 'friend': 1,
 'prepare': 1,
 'disturb': 1,
 'miss': 2,
 'assault': 1,
 'settle': 3,
 'quit': 2,
 'rip': 1,
 'dunhill': 1,
 'smart': 1,
 'maid': 1,
 'buss': 2,
 'grief': 1,
 'allow': 4,
 'couple': 1,
 'waistcoat': 1,
 'requisite': 1,
 'dream': 2,
 'contrive': 1,
 'purge': 2,
 'quicken': 1,
 'sweep': 1,
 'plot': 1,
 'inspire': 1,
 'eke': 1,
 'shut': 2,
 'grieve': 2,
 'molest': 1,
 'step': 1,
 'borrow': 1,
 'refuse': 1,
 'durst': 1,
 'deny': 3,
 'dote': 1,
 'debauch': 1,
 'feign': 1,
 'mew': 1,
 'prevaricate': 1,
 'willinger': 1,
 'kick': 3,
 'head': 1,
 'mediate': 1,
 'forswear': 1,
 'forbear': 1,
 'sir': 2,
 'addict': 1,
 'profit': 1,
 'teach': 2,
 'sin': 2,
 'vexation': 1,
 'cap': 1,
 'select': 1,
 'bezzle': 1,
 'recall': 1,
 'spirit': 1,
 'challenge': 1,
 'approve': 1,
 'unlove': 1,
 'construe': 1,
 'pierce': 1,
 'bleed': 2,
 'split': 2,
 'mince': 1,
 'change': 1,
 'mock': 2,
 'twitter': 1,
 'strike': 1,
 'fing’re': 1,
 'off’re': 1,
 'drive': 2,
 'Nay': 2,
 'affect': 1,
 'vex': 2,
 'forfeit': 1,
 'entreat': 1,
 'number': 1,
 'nee': 1,
 'outrun': 1,
 'shed': 2,
 'point': 2,
 'multiply': 1,
 'rut': 1,
 'snatch': 1,
 'forsake': 1,
 'hire': 1,
 'stir': 1,
 'dog': 1,
 'eye': 1,
 '’re': 1,
 'sever': 1,
 'beg': 1,
 'employ': 1,
 'belong': 1,
 'weep': 6,
 'resist': 1,
 'prefer': 1,
 'perfect': 1,
 'ripen': 1,
 'breed': 1,
 'plow': 1,
 'gather': 1,
 'spare': 2,
 'square': 1,
 'Come': 1,
 'language': 1,
 'travel': 1,
 'trust': 3,
 'govern': 1,
 'fool': 2,
 'horse': 2,
 'commit': 1,
 'dissemble': 1,
 'crack': 1,
 'disobey': 1,
 'heal': 1,
 'sicken': 1,
 'need': 2,
 'debate': 1,
 'lend': 1,
 'piss': 1,
 'hurry': 1,
 'humble': 1,
 'scorn': 1,
 'spit': 1,
 'contemn': 1,
 'pawn': 1,
 'strew': 1,
 'jumble': 1,
 'translate': 1,
 'unaske': 1,
 'part': 1,
 'wrong': 1,
 'beggar': 1,
 'subscribe': 2,
 'afford': 1,
 'reason': 1,
 'stink': 2,
 'needs': 1,
 'receive': 1,
 'drown': 2,
 'amien': 1,
 'shield': 1,
 'sing': 1,
 'mourn': 1,
 'lisp': 1,
 'mend': 2,
 'stone': 1,
 'ipso': 1,
 'discharge': 1,
 'boot': 1,
 'trifle': 1,
 'liest': 1,
 'remove': 1,
 'cause': 2,
 'move': 1,
 'judge': 1,
 'covet': 1,
 'defend': 1,
 'wretche': 1,
 'beget': 1,
 'rest': 1,
 'outlive': 1,
 'dedicate': 1,
 'pipe': 1,
 'frown': 1,
 'trick': 1,
 'overreach': 1,
 'curtail': 1}

In [ ]:
sorted_verbs_by_freq = sorted(b.items(), key=lambda x:x[1])

In [ ]:
print(sorted_verbs_by_freq[698:708])

[('think', 63), ('take', 63), ('know', 74), ('let', 75), ('’', 79), ('go', 79), ('come', 83), ('make', 93), ('do', 110), ('have', 152)]

In [ ]:
#seperating by male and female didn't work like this, create slices instead
df_women = df2['speaker_gender'] == 'F'
df_men = df2['speaker_gender'] == 'M'

In [ ]:
verb_lemma_list_male = []

for index, row in df2.iterrows():
  if row['speaker_gender'] == 'M':
      for word in row['verb_lemmas']:
        verb_lemma_list_male.append(word)

In [ ]:
verb_lemma_list_female = []
for index, row in df2.iterrows():
  if row['speaker_gender'] == 'F':
      for word in row['verb_lemmas']:
        verb_lemma_list_female.append(word)

In [ ]:
m = {}
for item in verb_lemma_list_male:
    m[item] = m.get(item, 0) + 1

sorted_m_verbs_by_freq = sorted(m.items(), key=lambda x:x[1])

In [ ]:
f = {}
for item in verb_lemma_list_female:
    f[item] = f.get(item, 0) + 1

sorted_f_verbs_by_freq = sorted(f.items(), key=lambda x:x[1])

In [ ]:
print(sorted_f_verbs_by_freq[382:392])

[('love', 24), ('take', 24), ('come', 25), ('let', 27), ('go', 27), ('’', 29), ('know', 36), ('make', 45), ('do', 46), ('have', 47)]

In [ ]:
print(sorted_m_verbs_by_freq[541:551])

[('tell', 41), ('think', 42), ('see', 43), ('go', 47), ('let', 47), ('’', 48), ('make', 48), ('come', 58), ('do', 64), ('have', 104)]

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df_female_subjects = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/honors thesis/new df male, female etc/df_female_subjects.csv')
df_male_subjects = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/honors thesis/new df male, female etc/df_male_subjects.csv')
df_with_i = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/honors thesis/new df male, female etc/df_with_i.csv')
df_tamertamed = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/honors thesis/new df male, female etc/df_2.csv')

In [ ]:
verb_lemma_list_female_s = []
for index, row in df_female_subjects.iterrows():
      for word in row['verb_lemmas_sentence']:
        verb_lemma_list_female_s.append(word)

In [ ]:
verb_lemma_list_male_s = []
for index, row in df_male_subjects.iterrows():
      for word in row['verb_lemmas_sentence']:
        verb_lemma_list_male_s.append(word)

In [ ]:
ms = {}
for item in verb_lemma_list_male_s:
    ms[item] = ms.get(item, 0) + 1

sorted_ms_verbs_by_freq = sorted(ms.items(), key=lambda x:x[1])

In [ ]:
fs = {}
for item in verb_lemma_list_female_s:
    fs[item] = fs.get(item, 0) + 1

sorted_fs_verbs_by_freq = sorted(fs.items(), key=lambda x:x[1])

In [ ]:
print(sorted_fs_verbs_by_freq[301:311])

[('tell', 21), ('see', 22), ('give', 22), ('say', 25), ('take', 25), ('think', 25), ('know', 27), ('make', 49), ('do', 53), ('have', 54)]

In [ ]:
print(sorted_ms_verbs_by_freq[242:252])

[('bear', 15), ('come', 15), ('say', 16), ('do', 20), ('know', 21), ('think', 25), ('let', 38), ('’', 43), ('make', 43), ('have', 59)]

In [ ]:
#read in Power Frames dataframe from csv to Pandas

gdown.download('https://drive.google.com/uc?export=download&id=1uF10Y-75-upMJyrte7uGXpsZM10RCcPz', quiet=False) 

df_powerframes = pd.read_csv('agency_power.csv')

print(df_powerframes)

Downloading...
From: https://drive.google.com/uc?export=download&id=1uF10Y-75-upMJyrte7uGXpsZM10RCcPz
To: /content/agency_power.csv
100%|██████████| 62.4k/62.4k [00:00<00:00, 46.0MB/s]

             verb        agency        power
0        abandons    agency_pos  power_agent
1       abolishes    agency_pos  power_agent
2         absorbs    agency_pos  power_agent
3          abuses    agency_pos  power_agent
4     accelerates    agency_pos  power_agent
...           ...           ...          ...
2150        yelps    agency_pos          NaN
2151       yields  agency_equal  power_agent
2152         zaps    agency_pos  power_agent
2153         zips    agency_pos          NaN
2154        zooms    agency_pos          NaN

[2155 rows x 3 columns]

In [ ]:
#lemmatize the powerframes dataframe verbs

import spacy
import en_core_web_sm
nlp = en_core_web_sm.load()

/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py:497: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")

In [ ]:
# Hi Becca! 
# From your email, it seems that you're having trouble adding a new column with the lemmas that you've created above... right?
# If so, here's how I'd modify your code to do that:


# add a new column to the df where we'll put the lemmas
df_powerframes['lemma'] = " "

#for rows in df_powerframes:
  #for row in rows:

# don't need a list since we'll just add the lemma to the row at the same time we lemmatize the word
# powerframe_lemmas = []

for index, row in df_powerframes.iterrows():
  doc = nlp(str(row['verb']))

  for word in doc:
# don't need this anymore since we're not using a list 
#    powerframe_lemmas.append(word.lemma_)

    # just add it directly to the df
     row['lemma'] = str(word.lemma_) 
  
#print(powerframe_lemmas)

# type(powerframe_lemmas)

df_powerframes

             verb        agency        power       lemma
0        abandons    agency_pos  power_agent     abandon
1       abolishes    agency_pos  power_agent    abolishe
2         absorbs    agency_pos  power_agent      absorb
3          abuses    agency_pos  power_agent       abuse
4     accelerates    agency_pos  power_agent  accelerate
...           ...           ...          ...         ...
2150        yelps    agency_pos          NaN        yelp
2151       yields  agency_equal  power_agent       yield
2152         zaps    agency_pos  power_agent        zaps
2153         zips    agency_pos          NaN         zip
2154        zooms    agency_pos          NaN        zoom

[2155 rows x 4 columns]

In [ ]:
#Setting up for the Tamer Tamed also...

# add a new column to the df where we'll put the list of verb lemmas
df_tamertamed['verb_lemmas'] = " "

for index, row in df_tamertamed.iterrows():
  doc2 = nlp(str(row['sentence']))
  verbs = []
  for word in doc2:
    if word.pos_ == 'VERB':
      verbs.append(word.lemma_)

  #  df_tamertamed.at[index, 'verbs'] = Verbs

  # try this:
  df_tamertamed.at[index, 'verb_lemmas_sentence'] = verbs
  
df_tamertamed

,Unnamed: 0,Unnamed: 0.1,index,id,speaker,direction_type,position,act,scene,text,...,power_theme,speaker_gender,character_list,sd_gender,male_gender_count,female_gender_count,subjects,male_subject_match,female_subject_match,verb_lemmas_sentence
0,0,0,0,stg-0006,NaN,entrance,0,1,1,"Enter Moroso , Sophocles , and Tranio , with R...",...,0.0,NaN,"['Moroso', 'Sophocles', 'Tranio']","['M', 'M', 'M']",3.0,0.0,NaN,NaN,NaN,enter
1,1,1,1,sp-0008,Moroso,NaN,1,1,1,. GOd give ’em joy .,...,0.0,M,[],[],0.0,0.0,GOd,NaN,NaN,[give]
2,2,2,2,sp-0010,Tranio,NaN,2,1,1,Amen .,...,0.0,M,[],[],0.0,0.0,NaN,NaN,NaN,[]
3,3,3,3,sp-0011,Sophocles,NaN,3,1,1,"Amen , say I too : The Puddings now i’ th’ pro...",...,0.0,M,[],[],0.0,0.0,I,NaN,NaN,"[say, thou]"
4,3,3,3,sp-0011,Sophocles,NaN,3,1,1,"Amen , say I too : The Puddings now i’ th’ pro...",...,0.0,M,[],[],0.0,0.0,Puddings,NaN,NaN,"[say, thou]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3526,1724,1724,1420,sp-3401,Petruchio,NaN,1420,5,4,"Let’s in , and drink of all hands , and be jov...",...,0.0,M,[],[],0.0,0.0,she,NaN,she,"[let, drink, have, carry, marry, let, keep]"
3527,1724,1724,1420,sp-3401,Petruchio,NaN,1420,5,4,"Let’s in , and drink of all hands , and be jov...",...,0.0,M,[],[],0.0,0.0,whoever,NaN,NaN,"[let, drink, have, carry, marry, let, keep]"
3528,1724,1724,1420,sp-3401,Petruchio,NaN,1420,5,4,"Let’s in , and drink of all hands , and be jov...",...,0.0,M,[],[],0.0,0.0,him,him,NaN,"[let, drink, have, carry, marry, let, keep]"
3529,1724,1724,1420,sp-3401,Petruchio,NaN,1420,5,4,"Let’s in , and drink of all hands , and be jov...",...,0.0,M,[],[],0.0,0.0,he,he,NaN,"[let, drink, have, carry, marry, let, keep]"
3530,1725,1725,1421,stg-3404,NaN,exit,1421,5,4,Exeunt .,...,0.0,NaN,[],[],0.0,0.0,NaN,NaN,NaN,[]

In [ ]:
#Setting up for the Tamer Tamed also...

# add a new column to the df where we'll put the list of verb lemmas
df_male_subjects['verb_lemmas_sentence'] = " "

for index, row in df_male_subjects.iterrows():
  doc2 = nlp(str(row['sentence']))
  verbs = []
  for word in doc2:
    if word.pos_ == 'VERB':
      verbs.append(word.lemma_)

  #  df_tamertamed.at[index, 'verbs'] = Verbs

  # try this:
  df_male_subjects.at[index, 'verb_lemmas_sentence'] = verbs
  
df_male_subjects

,Unnamed: 0,Unnamed: 0.1,index,id,speaker,direction_type,position,act,scene,text,...,power_theme,speaker_gender,character_list,sd_gender,male_gender_count,female_gender_count,subjects,male_subject_match,female_subject_match,verb_lemmas_sentence
0,4,4,4,sp-0016,Tranio,NaN,4,1,1,"’Tis too true : Certain , Methinks her father ...",...,0.0,M,[],[],0.0,0.0,father,father,NaN,"[tis, deal, exceed, match, protest, pity]"
1,5,5,5,sp-0021,Moroso,NaN,5,1,1,"Methinks now , He’s not so terrible as people ...",...,0.0,M,[],[],0.0,0.0,He,He,NaN,"[’, think]"
2,7,7,7,sp-0025,Tranio,NaN,7,1,1,But shall he have her ?,...,0.0,M,[],[],0.0,0.0,he,he,NaN,[have]
3,9,9,8,sp-0026,Sophocles,NaN,8,1,1,"Yes , when I have Rome . And yet the father’s ...",...,0.0,M,[],[],0.0,0.0,father,father,NaN,[’]
4,11,11,10,sp-0030,Sophocles,NaN,10,1,1,"Yes sure a wealthy , But whether a good woman’...",...,0.0,M,[],[],0.0,0.0,man,man,NaN,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,1682,1682,1385,sp-3335,Petronius,NaN,1385,5,4,"Go to him whore ; — if he perish , I’ll see th...",...,0.0,M,[],[],0.0,0.0,he,he,NaN,"[go, perish, see, hang]"
153,1698,1698,1397,sp-3357,Petruchio,NaN,1397,5,4,"Go Jaques , Get all the best meat may be bough...",...,2.0,M,[],[],0.0,0.0,he,he,NaN,"[go, get, buy, let, bear, see, wish, butter, b..."
154,1717,1717,1413,sp-3386,Petruchio,NaN,1413,5,4,"A match then , I’ll be the maker up of this : ...",...,0.0,M,['Moroso'],['M'],1.0,0.0,he,he,NaN,"[’, see, have]"
155,1724,1724,1420,sp-3401,Petruchio,NaN,1420,5,4,"Let’s in , and drink of all hands , and be jov...",...,0.0,M,[],[],0.0,0.0,him,him,NaN,"[let, drink, have, carry, marry, let, keep]"
156,1724,1724,1420,sp-3401,Petruchio,NaN,1420,5,4,"Let’s in , and drink of all hands , and be jov...",...,0.0,M,[],[],0.0,0.0,he,he,NaN,"[let, drink, have, carry, marry, let, keep]"

In [ ]:
#Setting up for the Tamer Tamed also...

# add a new column to the df where we'll put the list of verb lemmas
df_female_subjects['verb_lemmas_sentence'] = " "

for index, row in df_female_subjects.iterrows():
  doc2 = nlp(str(row['sentence']))
  verbs = []
  for word in doc2:
    if word.pos_ == 'VERB':
      verbs.append(word.lemma_)

  #  df_tamertamed.at[index, 'verbs'] = Verbs

  # try this:
  df_female_subjects.at[index, 'verb_lemmas_sentence'] = verbs
  
df_female_subjects

,Unnamed: 0,Unnamed: 0.1,index,id,speaker,direction_type,position,act,scene,text,...,power_theme,speaker_gender,character_list,sd_gender,male_gender_count,female_gender_count,subjects,male_subject_match,female_subject_match,verb_lemmas_sentence
0,13,13,12,sp-0033,Moroso,NaN,12,1,1,"What though his other wife , Out of her most a...",...,1.0,M,[],[],0.0,0.0,wife,NaN,wife,"[turn, force, blow]"
1,13,13,12,sp-0033,Moroso,NaN,12,1,1,"What though his other wife , Out of her most a...",...,1.0,M,[],[],0.0,0.0,she,NaN,she,"[turn, force, blow]"
2,18,18,16,sp-0045,Tranio,NaN,16,1,1,"I would learn to eat Coals with an angry Cat ,...",...,1.0,M,[],[],0.0,0.0,whore,NaN,whore,"[learn, eat, prevent, roar, tumble, tremble, be]"
3,23,23,20,sp-0063,Tranio,NaN,20,1,1,"His very frown , if she but say her prayers Lo...",...,0.0,M,[],[],0.0,0.0,she,NaN,she,"[say, talk, make, ’, do, eat, drink, say, make..."
4,23,23,20,sp-0063,Tranio,NaN,20,1,1,"His very frown , if she but say her prayers Lo...",...,0.0,M,[],[],0.0,0.0,She,NaN,She,"[say, talk, make, ’, do, eat, drink, say, make..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250,1626,1626,1342,sp-3218,Jaques,NaN,1342,5,2,"Stone her to death : may all she eat be Eggs ,...",...,0.0,M,[],[],0.0,0.0,she,NaN,she,"[stone, eat, run, kick]"
251,1626,1626,1342,sp-3218,Jaques,NaN,1342,5,2,"Stone her to death : may all she eat be Eggs ,...",...,0.0,M,[],[],0.0,0.0,she,NaN,she,"[stone, eat, run, kick]"
252,1631,1631,1347,sp-3230,Rowland,NaN,1347,5,3,What a dull ass was I to let her go thus ? Upo...,...,2.0,M,[],[],0.0,0.0,her,NaN,her,"[let, go]"
253,1632,1632,1347,sp-3230,Rowland,NaN,1347,5,3,What a dull ass was I to let her go thus ? Upo...,...,2.0,M,['Livia'],['F'],0.0,1.0,she,NaN,she,"[love, leave, lose, let, kiss, take, leave]"
254,1724,1724,1420,sp-3401,Petruchio,NaN,1420,5,4,"Let’s in , and drink of all hands , and be jov...",...,0.0,M,[],[],0.0,0.0,she,NaN,she,"[let, drink, have, carry, marry, let, keep]"